<a href="https://colab.research.google.com/github/charan2909/NN_ICP3/blob/main/700754801_ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# created a random vector of size 20 with float values between 1 and 20
ranvec = np.random.uniform(low=1, high=20, size=20)
print(ranvec)
# reshape the array to 4 by 5 using reshape method
mat45 = ranvec.reshape(4, 5)
print(mat45)
# replace the max in each row by 0 using where method
mat45 = np.where(mat45 == np.amax(mat45, axis=1, keepdims=True), 0, mat45)
print(mat45)

[ 4.62390815 13.58509212  1.26116941 14.20363609  3.5079674   2.76292978
 10.59627363  9.82830551 11.76242953  3.77701345 14.08798519  4.3671414
 12.36854748  6.46712844  8.27134165  5.71897575 15.57315792 14.45392867
  9.38026884  3.21638416]
[[ 4.62390815 13.58509212  1.26116941 14.20363609  3.5079674 ]
 [ 2.76292978 10.59627363  9.82830551 11.76242953  3.77701345]
 [14.08798519  4.3671414  12.36854748  6.46712844  8.27134165]
 [ 5.71897575 15.57315792 14.45392867  9.38026884  3.21638416]]
[[ 4.62390815 13.58509212  1.26116941  0.          3.5079674 ]
 [ 2.76292978 10.59627363  9.82830551  0.          3.77701345]
 [ 0.          4.3671414  12.36854748  6.46712844  8.27134165]
 [ 5.71897575  0.         14.45392867  9.38026884  3.21638416]]


In [6]:
class Employee:

    # declared a data member to count the number of Employees
    no_of_employees = 0

    # constructor to initialize the object's attributes
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1

    # declared average_salary function to return average salary
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees

# Created a Fulltime Employee class and inherited the properties of Employee class
class FulltimeEmployee(Employee):
    """
    Full Time Employee is a sub class of Employee
    """

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_member(self):
        print("Calling FulltimeEmployee member function.")

# Created the instances of Fulltime Employee class and Employee class and calling their member functions.
def main():
    employees = []
    ftEmployee1 = FulltimeEmployee("charan", "kamasani", 170000, "Data Engineer")
    ftEmployee1.full_time_member()
    employees.append(ftEmployee1)
    ftEmployee2 = FulltimeEmployee("uday", "kamasani", 190000, "devoleper")
    employees.append(ftEmployee2)
    employee1 = Employee("manoj", "gurram", 150000, "full stack devoleper")
    employees.append(employee1)
    employee2 = Employee("pradeep", "bala", 290000, "Product Manager")
    employees.append(employee2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))

# declared this method to execute code When the file runs as a script.
if __name__ == "__main__":
    main()

Calling FulltimeEmployee member function.
Average salary: 200000.0
