<a href="https://colab.research.google.com/github/charan2909/NN_ICP3/blob/main/700754801_ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a class Employee and then do the following

 • Create a data member to count the number of Employees


 • Create a constructor to initialize name, family, salary, department

 • Create a function to average salary

 • Create a Fulltime Employee class and it should inherit the properties of Employee class

 • Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [20]:
class Employee:

    # declared a data member to count the number of Employees
    #initializing to 0
    employee_count = 0

    # constructor to initialize the object's attributes
    def __init__(self, name, family, salary, department):
        self.name = name
        #self is a instance of class
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    # declared average_salary function to return average salary
    def average_salary(employees):
        """
        function to average salary
        """
        sum = 0
        for employee in employees:
            sum =sum + employee.salary
        return sum / Employee.employee_count

# Created a Fulltime Employee class and inherited the properties of Employee class
class FulltimeEmployee(Employee):


    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

    def full_time_member(self):
        print("Calling FulltimeEmployee member function.")

# Created the instances of Fulltime Employee class and Employee class and calling their member functions.
def main():
    employees = []
    fulltEmployee1 = FulltimeEmployee("charan", "kamasani", 170000, "Data Engineer")
    fulltEmployee1.full_time_member()
    employees.append(fulltEmployee1)
    fulltEmployee2 = FulltimeEmployee("uday", "kamasani", 190000, "devoleper")
    employees.append(fulltEmployee2)
    employee1 = Employee("manoj", "gurram", 150000, "full stack devoleper")
    employees.append(employee1)
    employee2 = Employee("pradeep", "bala", 290000, "Product Manager")
    employees.append(employee2)
    print("Average salary: ", FulltimeEmployee.average_salary(employees))

# declared this method to execute code When the file runs as a script.
if __name__ == "__main__":
    main()

Calling FulltimeEmployee member function.
Average salary:  200000.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

(you can NOT implement it via for loop)

In [10]:
import numpy as np

# created a random vector of size 20 with float values between 1 and 20
rangevec = np.random.uniform(low=1, high=20, size=20)
print(rangevec)
# reshape the array to 4 by 5 using reshape method
new = rangevec.reshape(4, 5)
print(new)
# replace the max in each row by 0 using where method
new = np.where(new == np.amax(new, axis=1, keepdims=True), 0, new)
print(new)

[16.45383302  1.72013947 18.1449756  16.57558733  2.15676662 14.69060881
  5.98238988  1.81005091 16.08702197  8.34444024 14.35570331  4.143382
  3.62487224 17.47229624  8.72502965 19.9575404  13.02584553  2.9342971
 11.58001766 17.0270575 ]
[[16.45383302  1.72013947 18.1449756  16.57558733  2.15676662]
 [14.69060881  5.98238988  1.81005091 16.08702197  8.34444024]
 [14.35570331  4.143382    3.62487224 17.47229624  8.72502965]
 [19.9575404  13.02584553  2.9342971  11.58001766 17.0270575 ]]
[[16.45383302  1.72013947  0.         16.57558733  2.15676662]
 [14.69060881  5.98238988  1.81005091  0.          8.34444024]
 [14.35570331  4.143382    3.62487224  0.          8.72502965]
 [ 0.         13.02584553  2.9342971  11.58001766 17.0270575 ]]
